[tool.black]
line-length = 119
target-version = ['py311']
exclude = '''
/(
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"

[flake8]
max-line-length = 119
extend-ignore = "E203, W503"  # E203 and W503 conflict with Black
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.blacken-docs]
line-length = 119

[tool.black.version]
format = "py311"
